// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umvuqbeuzjqmmudkvscy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdnVxYmV1empxbW11ZGt2c2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDA4MTEsImV4cCI6MjA1Nzk3NjgxMX0.Wqd9khQ_YuEpl1fFTuK6NVXv2JECmROLfHRDA7KoNpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);