"use client";
import { useState } from "react";

export default function SalaryAnalysisFormPage() {
  const [step, setStep] = useState(1);
  const [form, setForm] = useState<any>({ workloadPercent: 100, hasLeadership: false });
  const [error, setError] = useState("");
  const next = () => setStep((s) => Math.min(s + 1, 6));
  const prev = () => setStep((s) => Math.max(s - 1, 1));
  const submit = async () => { const r = await fetch('/api/salary-analysis/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const d=await r.json(); if(!r.ok) return setError(d.error||'Fehler'); window.location.href=`/salary-analysis/result/${d.id}?token=${d.accessToken}`; };
  return <main className="min-h-screen bg-[#F8FAFC] p-4"><div className="max-w-3xl mx-auto bg-white rounded-2xl p-6 border"><h1 className="text-2xl font-semibold mb-4">Lohnanalyse Formular (Schritt {step}/6)</h1>{error && <p className="text-red-600">{error}</p>}<div className="grid gap-3">{step===1&&<><input placeholder="Vorname *" className="border p-3 rounded" onChange={e=>setForm({...form,firstName:e.target.value})}/><input placeholder="Nachname *" className="border p-3 rounded" onChange={e=>setForm({...form,lastName:e.target.value})}/><input placeholder="E-Mail *" className="border p-3 rounded" onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="E-Mail bestätigen *" className="border p-3 rounded" onChange={e=>setForm({...form,emailConfirmation:e.target.value})}/></>}{step===2&&<><input placeholder="Jobtitel *" className="border p-3 rounded" onChange={e=>setForm({...form,jobTitle:e.target.value})}/><input placeholder="Branche *" className="border p-3 rounded" onChange={e=>setForm({...form,industry:e.target.value})}/><input placeholder="Berufserfahrung in Jahren *" className="border p-3 rounded" onChange={e=>setForm({...form,experienceYears:e.target.value})}/></>}{step===3&&<><input placeholder="Bruttojahreslohn" className="border p-3 rounded" onChange={e=>setForm({...form,annualGrossSalary:e.target.value})}/><input placeholder="Bruttomonatslohn" className="border p-3 rounded" onChange={e=>setForm({...form,monthlyGrossSalary:e.target.value})}/></>}{step===6&&<p className="text-sm text-[#475569]">Die Analyse basiert auf den bereitgestellten Angaben und öffentlich verfügbaren Benchmarkdaten.</p>}</div><div className="flex gap-2 mt-6">{step>1&&<button onClick={prev} className="border px-4 py-2 rounded">Zurück</button>}{step<6?<button onClick={next} className="bg-[#204878] text-white px-4 py-2 rounded">Weiter</button>:<button onClick={submit} className="bg-[#204878] text-white px-4 py-2 rounded">Lohnanalyse generieren</button>}</div></div></main>;
}
